export interface Country {
  id: string;
  name: string;
  emoji: string;
  slug: string;
}

export const countries: Country[] = [
  {
    id: "af",
    name: "Afghanistan",
    emoji: "🇦🇫",
    slug: "afghanistan",
  },
  {
    id: "al",
    name: "Albania",
    emoji: "🇦🇱",
    slug: "albania",
  },
  {
    id: "dz",
    name: "Algeria",
    emoji: "🇩🇿",
    slug: "algeria",
  },
  {
    id: "ad",
    name: "Andorra",
    emoji: "🇦🇩",
    slug: "andorra",
  },
  {
    id: "ao",
    name: "Angola",
    emoji: "🇦🇴",
    slug: "angola",
  },
  {
    id: "ag",
    name: "Antigua and Barbuda",
    emoji: "🇦🇬",
    slug: "antigua-and-barbuda",
  },
  {
    id: "ar",
    name: "Argentina",
    emoji: "🇦🇷",
    slug: "argentina",
  },
  {
    id: "am",
    name: "Armenia",
    emoji: "🇦🇲",
    slug: "armenia",
  },
  {
    id: "au",
    name: "Australia",
    emoji: "🇦🇺",
    slug: "australia",
  },
  {
    id: "at",
    name: "Austria",
    emoji: "🇦🇹",
    slug: "austria",
  },
  {
    id: "az",
    name: "Azerbaijan",
    emoji: "🇦🇿",
    slug: "azerbaijan",
  },
  {
    id: "bs",
    name: "Bahamas",
    emoji: "🇧🇸",
    slug: "bahamas",
  },
  {
    id: "bh",
    name: "Bahrain",
    emoji: "🇧🇭",
    slug: "bahrain",
  },
  {
    id: "bd",
    name: "Bangladesh",
    emoji: "🇧🇩",
    slug: "bangladesh",
  },
  {
    id: "bb",
    name: "Barbados",
    emoji: "🇧🇧",
    slug: "barbados",
  },
  {
    id: "by",
    name: "Belarus",
    emoji: "🇧🇾",
    slug: "belarus",
  },
  {
    id: "be",
    name: "Belgium",
    emoji: "🇧🇪",
    slug: "belgium",
  },
  {
    id: "bz",
    name: "Belize",
    emoji: "🇧🇿",
    slug: "belize",
  },
  {
    id: "bj",
    name: "Benin",
    emoji: "🇧🇯",
    slug: "benin",
  },
  {
    id: "bt",
    name: "Bhutan",
    emoji: "🇧🇹",
    slug: "bhutan",
  },
  {
    id: "bo",
    name: "Bolivia",
    emoji: "🇧🇴",
    slug: "bolivia",
  },
  {
    id: "ba",
    name: "Bosnia and Herzegovina",
    emoji: "🇧🇦",
    slug: "bosnia-and-herzegovina",
  },
  {
    id: "bw",
    name: "Botswana",
    emoji: "🇧🇼",
    slug: "botswana",
  },
  {
    id: "br",
    name: "Brazil",
    emoji: "🇧🇷",
    slug: "brazil",
  },
  {
    id: "bn",
    name: "Brunei Darussalam",
    emoji: "🇧🇳",
    slug: "brunei",
  },
  {
    id: "bg",
    name: "Bulgaria",
    emoji: "🇧🇬",
    slug: "bulgaria",
  },
  {
    id: "bf",
    name: "Burkina Faso",
    emoji: "🇧🇫",
    slug: "burkina-faso",
  },
  {
    id: "bi",
    name: "Burundi",
    emoji: "🇧🇮",
    slug: "burundi",
  },
  {
    id: "cv",
    name: "Cabo Verde",
    emoji: "🇨🇻",
    slug: "cabo-verde",
  },
  {
    id: "kh",
    name: "Cambodia",
    emoji: "🇰🇭",
    slug: "cambodia",
  },
  {
    id: "cm",
    name: "Cameroon",
    emoji: "🇨🇲",
    slug: "cameroon",
  },
  {
    id: "ca",
    name: "Canada",
    emoji: "🇨🇦",
    slug: "canada",
  },
  {
    id: "cf",
    name: "Central African Republic",
    emoji: "🇨🇫",
    slug: "central-african-republic",
  },
  {
    id: "td",
    name: "Chad",
    emoji: "🇹🇩",
    slug: "chad",
  },
  {
    id: "cl",
    name: "Chile",
    emoji: "🇨🇱",
    slug: "chile",
  },
  {
    id: "cn",
    name: "China",
    emoji: "🇨🇳",
    slug: "china",
  },
  {
    id: "co",
    name: "Colombia",
    emoji: "🇨🇴",
    slug: "colombia",
  },
  {
    id: "km",
    name: "Comoros",
    emoji: "🇰🇲",
    slug: "comoros",
  },
  {
    id: "cg",
    name: "Congo",
    emoji: "🇨🇬",
    slug: "congo",
  },
  {
    id: "cd",
    name: "Democratic Republic of the Congo",
    emoji: "🇨🇩",
    slug: "drc",
  },
  {
    id: "cr",
    name: "Costa Rica",
    emoji: "🇨🇷",
    slug: "costa-rica",
  },
  {
    id: "ci",
    name: "Côte d'Ivoire",
    emoji: "🇨🇮",
    slug: "ivory-coast",
  },
  {
    id: "hr",
    name: "Croatia",
    emoji: "🇭🇷",
    slug: "croatia",
  },
  {
    id: "cu",
    name: "Cuba",
    emoji: "🇨🇺",
    slug: "cuba",
  },
  {
    id: "cy",
    name: "Cyprus",
    emoji: "🇨🇾",
    slug: "cyprus",
  },
  {
    id: "cz",
    name: "Czechia",
    emoji: "🇨🇿",
    slug: "czechia",
  },
  {
    id: "dk",
    name: "Denmark",
    emoji: "🇩🇰",
    slug: "denmark",
  },
  {
    id: "dj",
    name: "Djibouti",
    emoji: "🇩🇯",
    slug: "djibouti",
  },
  {
    id: "dm",
    name: "Dominica",
    emoji: "🇩🇲",
    slug: "dominica",
  },
  {
    id: "do",
    name: "Dominican Republic",
    emoji: "🇩🇴",
    slug: "dominican-republic",
  },
  {
    id: "ec",
    name: "Ecuador",
    emoji: "🇪🇨",
    slug: "ecuador",
  },
  {
    id: "eg",
    name: "Egypt",
    emoji: "🇪🇬",
    slug: "egypt",
  },
  {
    id: "sv",
    name: "El Salvador",
    emoji: "🇸🇻",
    slug: "el-salvador",
  },
  {
    id: "gq",
    name: "Equatorial Guinea",
    emoji: "🇬🇶",
    slug: "equatorial-guinea",
  },
  {
    id: "er",
    name: "Eritrea",
    emoji: "🇪🇷",
    slug: "eritrea",
  },
  {
    id: "ee",
    name: "Estonia",
    emoji: "🇪🇪",
    slug: "estonia",
  },
  {
    id: "sz",
    name: "Eswatini",
    emoji: "🇸🇿",
    slug: "eswatini",
  },
  {
    id: "et",
    name: "Ethiopia",
    emoji: "🇪🇹",
    slug: "ethiopia",
  },
  {
    id: "fj",
    name: "Fiji",
    emoji: "🇫🇯",
    slug: "fiji",
  },
  {
    id: "fi",
    name: "Finland",
    emoji: "🇫🇮",
    slug: "finland",
  },
  {
    id: "fr",
    name: "France",
    emoji: "🇫🇷",
    slug: "france",
  },
  {
    id: "ga",
    name: "Gabon",
    emoji: "🇬🇦",
    slug: "gabon",
  },
  {
    id: "gm",
    name: "Gambia",
    emoji: "🇬🇲",
    slug: "gambia",
  },
  {
    id: "ge",
    name: "Georgia",
    emoji: "🇬🇪",
    slug: "georgia",
  },
  {
    id: "de",
    name: "Germany",
    emoji: "🇩🇪",
    slug: "germany",
  },
  {
    id: "gh",
    name: "Ghana",
    emoji: "🇬🇭",
    slug: "ghana",
  },
  {
    id: "gr",
    name: "Greece",
    emoji: "🇬🇷",
    slug: "greece",
  },
  {
    id: "gd",
    name: "Grenada",
    emoji: "🇬🇩",
    slug: "grenada",
  },
  {
    id: "gt",
    name: "Guatemala",
    emoji: "🇬🇹",
    slug: "guatemala",
  },
  {
    id: "gn",
    name: "Guinea",
    emoji: "🇬🇳",
    slug: "guinea",
  },
  {
    id: "gw",
    name: "Guinea-Bissau",
    emoji: "🇬🇼",
    slug: "guinea-bissau",
  },
  {
    id: "gy",
    name: "Guyana",
    emoji: "🇬🇾",
    slug: "guyana",
  },
  {
    id: "ht",
    name: "Haiti",
    emoji: "🇭🇹",
    slug: "haiti",
  },
  {
    id: "hn",
    name: "Honduras",
    emoji: "🇭🇳",
    slug: "honduras",
  },
  {
    id: "hu",
    name: "Hungary",
    emoji: "🇭🇺",
    slug: "hungary",
  },
  {
    id: "is",
    name: "Iceland",
    emoji: "🇮🇸",
    slug: "iceland",
  },
  {
    id: "in",
    name: "India",
    emoji: "🇮🇳",
    slug: "india",
  },
  {
    id: "id",
    name: "Indonesia",
    emoji: "🇮🇩",
    slug: "indonesia",
  },
  {
    id: "ir",
    name: "Iran",
    emoji: "🇮🇷",
    slug: "iran",
  },
  {
    id: "iq",
    name: "Iraq",
    emoji: "🇮🇶",
    slug: "iraq",
  },
  {
    id: "ie",
    name: "Ireland",
    emoji: "🇮🇪",
    slug: "ireland",
  },
  {
    id: "il",
    name: "Israel",
    emoji: "🇮🇱",
    slug: "israel",
  },
  {
    id: "it",
    name: "Italy",
    emoji: "🇮🇹",
    slug: "italy",
  },
  {
    id: "jm",
    name: "Jamaica",
    emoji: "🇯🇲",
    slug: "jamaica",
  },
  {
    id: "jp",
    name: "Japan",
    emoji: "🇯🇵",
    slug: "japan",
  },
  {
    id: "jo",
    name: "Jordan",
    emoji: "🇯🇴",
    slug: "jordan",
  },
  {
    id: "kz",
    name: "Kazakhstan",
    emoji: "🇰🇿",
    slug: "kazakhstan",
  },
  {
    id: "ke",
    name: "Kenya",
    emoji: "🇰🇪",
    slug: "kenya",
  },
  {
    id: "ki",
    name: "Kiribati",
    emoji: "🇰🇮",
    slug: "kiribati",
  },
  {
    id: "kp",
    name: "North Korea",
    emoji: "🇰🇵",
    slug: "north-korea",
  },
  {
    id: "kr",
    name: "South Korea",
    emoji: "🇰🇷",
    slug: "south-korea",
  },
  {
    id: "kw",
    name: "Kuwait",
    emoji: "🇰🇼",
    slug: "kuwait",
  },
  {
    id: "kg",
    name: "Kyrgyzstan",
    emoji: "🇰🇬",
    slug: "kyrgyzstan",
  },
  {
    id: "la",
    name: "Laos",
    emoji: "🇱🇦",
    slug: "laos",
  },
  {
    id: "lv",
    name: "Latvia",
    emoji: "🇱🇻",
    slug: "latvia",
  },
  {
    id: "lb",
    name: "Lebanon",
    emoji: "🇱🇧",
    slug: "lebanon",
  },
  {
    id: "ls",
    name: "Lesotho",
    emoji: "🇱🇸",
    slug: "lesotho",
  },
  {
    id: "lr",
    name: "Liberia",
    emoji: "🇱🇷",
    slug: "liberia",
  },
  {
    id: "ly",
    name: "Libya",
    emoji: "🇱🇾",
    slug: "libya",
  },
  {
    id: "li",
    name: "Liechtenstein",
    emoji: "🇱🇮",
    slug: "liechtenstein",
  },
  {
    id: "lt",
    name: "Lithuania",
    emoji: "🇱🇹",
    slug: "lithuania",
  },
  {
    id: "lu",
    name: "Luxembourg",
    emoji: "🇱🇺",
    slug: "luxembourg",
  },
  {
    id: "mg",
    name: "Madagascar",
    emoji: "🇲🇬",
    slug: "madagascar",
  },
  {
    id: "mw",
    name: "Malawi",
    emoji: "🇲🇼",
    slug: "malawi",
  },
  {
    id: "my",
    name: "Malaysia",
    emoji: "🇲🇾",
    slug: "malaysia",
  },
  {
    id: "mv",
    name: "Maldives",
    emoji: "🇲🇻",
    slug: "maldives",
  },
  {
    id: "ml",
    name: "Mali",
    emoji: "🇲🇱",
    slug: "mali",
  },
  {
    id: "mt",
    name: "Malta",
    emoji: "🇲🇹",
    slug: "malta",
  },
  {
    id: "mh",
    name: "Marshall Islands",
    emoji: "🇲🇭",
    slug: "marshall-islands",
  },
  {
    id: "mr",
    name: "Mauritania",
    emoji: "🇲🇷",
    slug: "mauritania",
  },
  {
    id: "mu",
    name: "Mauritius",
    emoji: "🇲🇺",
    slug: "mauritius",
  },
  {
    id: "mx",
    name: "Mexico",
    emoji: "🇲🇽",
    slug: "mexico",
  },
  {
    id: "fm",
    name: "Micronesia",
    emoji: "🇫🇲",
    slug: "micronesia",
  },
  {
    id: "md",
    name: "Moldova",
    emoji: "🇲🇩",
    slug: "moldova",
  },
  {
    id: "mc",
    name: "Monaco",
    emoji: "🇲🇨",
    slug: "monaco",
  },
  {
    id: "mn",
    name: "Mongolia",
    emoji: "🇲🇳",
    slug: "mongolia",
  },
  {
    id: "me",
    name: "Montenegro",
    emoji: "🇲🇪",
    slug: "montenegro",
  },
  {
    id: "ma",
    name: "Morocco",
    emoji: "🇲🇦",
    slug: "morocco",
  },
  {
    id: "mz",
    name: "Mozambique",
    emoji: "🇲🇿",
    slug: "mozambique",
  },
  {
    id: "mm",
    name: "Myanmar",
    emoji: "🇲🇲",
    slug: "myanmar",
  },
  {
    id: "na",
    name: "Namibia",
    emoji: "🇳🇦",
    slug: "namibia",
  },
  {
    id: "nr",
    name: "Nauru",
    emoji: "🇳🇷",
    slug: "nauru",
  },
  {
    id: "np",
    name: "Nepal",
    emoji: "🇳🇵",
    slug: "nepal",
  },
  {
    id: "nl",
    name: "Netherlands",
    emoji: "🇳🇱",
    slug: "netherlands",
  },
  {
    id: "nz",
    name: "New Zealand",
    emoji: "🇳🇿",
    slug: "new-zealand",
  },
  {
    id: "ni",
    name: "Nicaragua",
    emoji: "🇳🇮",
    slug: "nicaragua",
  },
  {
    id: "ne",
    name: "Niger",
    emoji: "🇳🇪",
    slug: "niger",
  },
  {
    id: "ng",
    name: "Nigeria",
    emoji: "🇳🇬",
    slug: "nigeria",
  },
  {
    id: "mk",
    name: "North Macedonia",
    emoji: "🇲🇰",
    slug: "north-macedonia",
  },
  {
    id: "no",
    name: "Norway",
    emoji: "🇳🇴",
    slug: "norway",
  },
  {
    id: "om",
    name: "Oman",
    emoji: "🇴🇲",
    slug: "oman",
  },
  {
    id: "pk",
    name: "Pakistan",
    emoji: "🇵🇰",
    slug: "pakistan",
  },
  {
    id: "pw",
    name: "Palau",
    emoji: "🇵🇼",
    slug: "palau",
  },
  {
    id: "pa",
    name: "Panama",
    emoji: "🇵🇦",
    slug: "panama",
  },
  {
    id: "pg",
    name: "Papua New Guinea",
    emoji: "🇵🇬",
    slug: "papua-new-guinea",
  },
  {
    id: "py",
    name: "Paraguay",
    emoji: "🇵🇾",
    slug: "paraguay",
  },
  {
    id: "pe",
    name: "Peru",
    emoji: "🇵🇪",
    slug: "peru",
  },
  {
    id: "ph",
    name: "Philippines",
    emoji: "🇵🇭",
    slug: "philippines",
  },
  {
    id: "pl",
    name: "Poland",
    emoji: "🇵🇱",
    slug: "poland",
  },
  {
    id: "pt",
    name: "Portugal",
    emoji: "🇵🇹",
    slug: "portugal",
  },
  {
    id: "qa",
    name: "Qatar",
    emoji: "🇶🇦",
    slug: "qatar",
  },
  {
    id: "ro",
    name: "Romania",
    emoji: "🇷🇴",
    slug: "romania",
  },
  {
    id: "ru",
    name: "Russia",
    emoji: "🇷🇺",
    slug: "russia",
  },
  {
    id: "rw",
    name: "Rwanda",
    emoji: "🇷🇼",
    slug: "rwanda",
  },
  {
    id: "kn",
    name: "Saint Kitts and Nevis",
    emoji: "🇰🇳",
    slug: "saint-kitts-and-nevis",
  },
  {
    id: "lc",
    name: "Saint Lucia",
    emoji: "🇱🇨",
    slug: "saint-lucia",
  },
  {
    id: "vc",
    name: "Saint Vincent and the Grenadines",
    emoji: "🇻🇨",
    slug: "saint-vincent",
  },
  {
    id: "ws",
    name: "Samoa",
    emoji: "🇼🇸",
    slug: "samoa",
  },
  {
    id: "sm",
    name: "San Marino",
    emoji: "🇸🇲",
    slug: "san-marino",
  },
  {
    id: "st",
    name: "Sao Tome and Principe",
    emoji: "🇸🇹",
    slug: "sao-tome-and-principe",
  },
  {
    id: "sa",
    name: "Saudi Arabia",
    emoji: "🇸🇦",
    slug: "saudi-arabia",
  },
  {
    id: "sn",
    name: "Senegal",
    emoji: "🇸🇳",
    slug: "senegal",
  },
  {
    id: "rs",
    name: "Serbia",
    emoji: "🇷🇸",
    slug: "serbia",
  },
  {
    id: "sc",
    name: "Seychelles",
    emoji: "🇸🇨",
    slug: "seychelles",
  },
  {
    id: "sl",
    name: "Sierra Leone",
    emoji: "🇸🇱",
    slug: "sierra-leone",
  },
  {
    id: "sg",
    name: "Singapore",
    emoji: "🇸🇬",
    slug: "singapore",
  },
  {
    id: "sk",
    name: "Slovakia",
    emoji: "🇸🇰",
    slug: "slovakia",
  },
  {
    id: "si",
    name: "Slovenia",
    emoji: "🇸🇮",
    slug: "slovenia",
  },
  {
    id: "sb",
    name: "Solomon Islands",
    emoji: "🇸🇧",
    slug: "solomon-islands",
  },
  {
    id: "so",
    name: "Somalia",
    emoji: "🇸🇴",
    slug: "somalia",
  },
  {
    id: "za",
    name: "South Africa",
    emoji: "🇿🇦",
    slug: "south-africa",
  },
  {
    id: "ss",
    name: "South Sudan",
    emoji: "🇸🇸",
    slug: "south-sudan",
  },
  {
    id: "es",
    name: "Spain",
    emoji: "🇪🇸",
    slug: "spain",
  },
  {
    id: "lk",
    name: "Sri Lanka",
    emoji: "🇱🇰",
    slug: "sri-lanka",
  },
  {
    id: "sd",
    name: "Sudan",
    emoji: "🇸🇩",
    slug: "sudan",
  },
  {
    id: "sr",
    name: "Suriname",
    emoji: "🇸🇷",
    slug: "suriname",
  },
  {
    id: "se",
    name: "Sweden",
    emoji: "🇸🇪",
    slug: "sweden",
  },
  {
    id: "ch",
    name: "Switzerland",
    emoji: "🇨🇭",
    slug: "switzerland",
  },
  {
    id: "sy",
    name: "Syria",
    emoji: "🇸🇾",
    slug: "syria",
  },
  {
    id: "tj",
    name: "Tajikistan",
    emoji: "🇹🇯",
    slug: "tajikistan",
  },
  {
    id: "tz",
    name: "Tanzania",
    emoji: "🇹🇿",
    slug: "tanzania",
  },
  {
    id: "th",
    name: "Thailand",
    emoji: "🇹🇭",
    slug: "thailand",
  },
  {
    id: "tl",
    name: "Timor-Leste",
    emoji: "🇹🇱",
    slug: "timor-leste",
  },
  {
    id: "tg",
    name: "Togo",
    emoji: "🇹🇬",
    slug: "togo",
  },
  {
    id: "to",
    name: "Tonga",
    emoji: "🇹🇴",
    slug: "tonga",
  },
  {
    id: "tt",
    name: "Trinidad and Tobago",
    emoji: "🇹🇹",
    slug: "trinidad-and-tobago",
  },
  {
    id: "tn",
    name: "Tunisia",
    emoji: "🇹🇳",
    slug: "tunisia",
  },
  {
    id: "tr",
    name: "Türkiye",
    emoji: "🇹🇷",
    slug: "turkey",
  },
  {
    id: "tm",
    name: "Turkmenistan",
    emoji: "🇹🇲",
    slug: "turkmenistan",
  },
  {
    id: "tv",
    name: "Tuvalu",
    emoji: "🇹🇻",
    slug: "tuvalu",
  },
  {
    id: "ug",
    name: "Uganda",
    emoji: "🇺🇬",
    slug: "uganda",
  },
  {
    id: "ua",
    name: "Ukraine",
    emoji: "🇺🇦",
    slug: "ukraine",
  },
  {
    id: "ae",
    name: "United Arab Emirates",
    emoji: "🇦🇪",
    slug: "uae",
  },
  {
    id: "gb",
    name: "United Kingdom",
    emoji: "🇬🇧",
    slug: "united-kingdom",
  },
  {
    id: "us",
    name: "United States of America",
    emoji: "🇺🇸",
    slug: "united-states",
  },
  {
    id: "uy",
    name: "Uruguay",
    emoji: "🇺🇾",
    slug: "uruguay",
  },
  {
    id: "uz",
    name: "Uzbekistan",
    emoji: "🇺🇿",
    slug: "uzbekistan",
  },
  {
    id: "vu",
    name: "Vanuatu",
    emoji: "🇻🇺",
    slug: "vanuatu",
  },
  {
    id: "ve",
    name: "Venezuela",
    emoji: "🇻🇪",
    slug: "venezuela",
  },
  {
    id: "vn",
    name: "Vietnam",
    emoji: "🇻🇳",
    slug: "vietnam",
  },
  {
    id: "ye",
    name: "Yemen",
    emoji: "🇾🇪",
    slug: "yemen",
  },
  {
    id: "zm",
    name: "Zambia",
    emoji: "🇿🇲",
    slug: "zambia",
  },
  {
    id: "zw",
    name: "Zimbabwe",
    emoji: "🇿🇼",
    slug: "zimbabwe",
  },
];

export const countriesById = Object.fromEntries(
  countries.map((c) => [c.id, { name: c.name, emoji: c.emoji }])
);
