export const countries = [
  { id: "af", name: "Afghanistan" },
  { id: "al", name: "Albania" },
  { id: "dz", name: "Algeria" },
  { id: "ad", name: "Andorra" },
  { id: "ao", name: "Angola" },
  { id: "ag", name: "Antigua and Barbuda" },
  { id: "ar", name: "Argentina" },
  { id: "am", name: "Armenia" },
  { id: "au", name: "Australia" },
  { id: "at", name: "Austria" },
  { id: "az", name: "Azerbaijan" },
  { id: "bs", name: "Bahamas" },
  { id: "bh", name: "Bahrain" },
  { id: "bd", name: "Bangladesh" },
  { id: "bb", name: "Barbados" },
  { id: "by", name: "Belarus" },
  { id: "be", name: "Belgium" },
  { id: "bz", name: "Belize" },
  { id: "bj", name: "Benin" },
  { id: "bt", name: "Bhutan" },
  { id: "bo", name: "Bolivia, Plurinational State of" },
  { id: "ba", name: "Bosnia and Herzegovina" },
  { id: "bw", name: "Botswana" },
  { id: "br", name: "Brazil" },
  { id: "bn", name: "Brunei Darussalam" },
  { id: "bg", name: "Bulgaria" },
  { id: "bf", name: "Burkina Faso" },
  { id: "bi", name: "Burundi" },
  { id: "cv", name: "Cabo Verde" },
  { id: "kh", name: "Cambodia" },
  { id: "cm", name: "Cameroon" },
  { id: "ca", name: "Canada" },
  { id: "cf", name: "Central African Republic" },
  { id: "td", name: "Chad" },
  { id: "cl", name: "Chile" },
  { id: "cn", name: "China" },
  { id: "co", name: "Colombia" },
  { id: "km", name: "Comoros" },
  { id: "cg", name: "Congo" },
  { id: "cd", name: "Congo, Democratic Republic of the" },
  { id: "cr", name: "Costa Rica" },
  { id: "ci", name: "Côte d'Ivoire" },
  { id: "hr", name: "Croatia" },
  { id: "cu", name: "Cuba" },
  { id: "cy", name: "Cyprus" },
  { id: "cz", name: "Czechia" },
  { id: "dk", name: "Denmark" },
  { id: "dj", name: "Djibouti" },
  { id: "dm", name: "Dominica" },
  { id: "do", name: "Dominican Republic" },
  { id: "ec", name: "Ecuador" },
  { id: "eg", name: "Egypt" },
  { id: "sv", name: "El Salvador" },
  { id: "gq", name: "Equatorial Guinea" },
  { id: "er", name: "Eritrea" },
  { id: "ee", name: "Estonia" },
  { id: "sz", name: "Eswatini" },
  { id: "et", name: "Ethiopia" },
  { id: "fj", name: "Fiji" },
  { id: "fi", name: "Finland" },
  { id: "fr", name: "France" },
  { id: "ga", name: "Gabon" },
  { id: "gm", name: "Gambia" },
  { id: "ge", name: "Georgia" },
  { id: "de", name: "Germany" },
  { id: "gh", name: "Ghana" },
  { id: "gr", name: "Greece" },
  { id: "gd", name: "Grenada" },
  { id: "gt", name: "Guatemala" },
  { id: "gn", name: "Guinea" },
  { id: "gw", name: "Guinea-Bissau" },
  { id: "gy", name: "Guyana" },
  { id: "ht", name: "Haiti" },
  { id: "hn", name: "Honduras" },
  { id: "hu", name: "Hungary" },
  { id: "is", name: "Iceland" },
  { id: "in", name: "India" },
  { id: "id", name: "Indonesia" },
  { id: "ir", name: "Iran, Islamic Republic of" },
  { id: "iq", name: "Iraq" },
  { id: "ie", name: "Ireland" },
  { id: "il", name: "Israel" },
  { id: "it", name: "Italy" },
  { id: "jm", name: "Jamaica" },
  { id: "jp", name: "Japan" },
  { id: "jo", name: "Jordan" },
  { id: "kz", name: "Kazakhstan" },
  { id: "ke", name: "Kenya" },
  { id: "ki", name: "Kiribati" },
  { id: "kp", name: "Korea, Democratic People's Republic of" },
  { id: "kr", name: "Korea, Republic of" },
  { id: "kw", name: "Kuwait" },
  { id: "kg", name: "Kyrgyzstan" },
  { id: "la", name: "Lao People's Democratic Republic" },
  { id: "lv", name: "Latvia" },
  { id: "lb", name: "Lebanon" },
  { id: "ls", name: "Lesotho" },
  { id: "lr", name: "Liberia" },
  { id: "ly", name: "Libya" },
  { id: "li", name: "Liechtenstein" },
  { id: "lt", name: "Lithuania" },
  { id: "lu", name: "Luxembourg" },
  { id: "mg", name: "Madagascar" },
  { id: "mw", name: "Malawi" },
  { id: "my", name: "Malaysia" },
  { id: "mv", name: "Maldives" },
  { id: "ml", name: "Mali" },
  { id: "mt", name: "Malta" },
  { id: "mh", name: "Marshall Islands" },
  { id: "mr", name: "Mauritania" },
  { id: "mu", name: "Mauritius" },
  { id: "mx", name: "Mexico" },
  { id: "fm", name: "Micronesia, Federated States of" },
  { id: "md", name: "Moldova, Republic of" },
  { id: "mc", name: "Monaco" },
  { id: "mn", name: "Mongolia" },
  { id: "me", name: "Montenegro" },
  { id: "ma", name: "Morocco" },
  { id: "mz", name: "Mozambique" },
  { id: "mm", name: "Myanmar" },
  { id: "na", name: "Namibia" },
  { id: "nr", name: "Nauru" },
  { id: "np", name: "Nepal" },
  { id: "nl", name: "Netherlands" },
  { id: "nz", name: "New Zealand" },
  { id: "ni", name: "Nicaragua" },
  { id: "ne", name: "Niger" },
  { id: "ng", name: "Nigeria" },
  { id: "mk", name: "North Macedonia" },
  { id: "no", name: "Norway" },
  { id: "om", name: "Oman" },
  { id: "pk", name: "Pakistan" },
  { id: "pw", name: "Palau" },
  { id: "pa", name: "Panama" },
  { id: "pg", name: "Papua New Guinea" },
  { id: "py", name: "Paraguay" },
  { id: "pe", name: "Peru" },
  { id: "ph", name: "Philippines" },
  { id: "pl", name: "Poland" },
  { id: "pt", name: "Portugal" },
  { id: "qa", name: "Qatar" },
  { id: "ro", name: "Romania" },
  { id: "ru", name: "Russian Federation" },
  { id: "rw", name: "Rwanda" },
  { id: "kn", name: "Saint Kitts and Nevis" },
  { id: "lc", name: "Saint Lucia" },
  { id: "vc", name: "Saint Vincent and the Grenadines" },
  { id: "ws", name: "Samoa" },
  { id: "sm", name: "San Marino" },
  { id: "st", name: "Sao Tome and Principe" },
  { id: "sa", name: "Saudi Arabia" },
  { id: "sn", name: "Senegal" },
  { id: "rs", name: "Serbia" },
  { id: "sc", name: "Seychelles" },
  { id: "sl", name: "Sierra Leone" },
  { id: "sg", name: "Singapore" },
  { id: "sk", name: "Slovakia" },
  { id: "si", name: "Slovenia" },
  { id: "sb", name: "Solomon Islands" },
  { id: "so", name: "Somalia" },
  { id: "za", name: "South Africa" },
  { id: "ss", name: "South Sudan" },
  { id: "es", name: "Spain" },
  { id: "lk", name: "Sri Lanka" },
  { id: "sd", name: "Sudan" },
  { id: "sr", name: "Suriname" },
  { id: "se", name: "Sweden" },
  { id: "ch", name: "Switzerland" },
  { id: "sy", name: "Syrian Arab Republic" },
  { id: "tj", name: "Tajikistan" },
  { id: "tz", name: "Tanzania, United Republic of" },
  { id: "th", name: "Thailand" },
  { id: "tl", name: "Timor-Leste" },
  { id: "tg", name: "Togo" },
  { id: "to", name: "Tonga" },
  { id: "tt", name: "Trinidad and Tobago" },
  { id: "tn", name: "Tunisia" },
  { id: "tr", name: "Türkiye" },
  { id: "tm", name: "Turkmenistan" },
  { id: "tv", name: "Tuvalu" },
  { id: "ug", name: "Uganda" },
  { id: "ua", name: "Ukraine" },
  { id: "ae", name: "United Arab Emirates" },
  { id: "gb", name: "United Kingdom of Great Britain and Northern Ireland" },
  { id: "us", name: "United States of America" },
  { id: "uy", name: "Uruguay" },
  { id: "uz", name: "Uzbekistan" },
  { id: "vu", name: "Vanuatu" },
  { id: "ve", name: "Venezuela, Bolivarian Republic of" },
  { id: "vn", name: "Viet Nam" },
  { id: "ye", name: "Yemen" },
  { id: "zm", name: "Zambia" },
  { id: "zw", name: "Zimbabwe" },
];

export type VisaRequirementType =
  | "VISA_REQUIRED"
  | "VISA_NOT_REQUIRED"
  | "FREEDOM_OF_MOVEMENT"
  | "EVISA"
  | "VISA_ON_ARRIVAL"
  | null;

export function getVisaRequirementType(
  visaRequirement: string
): VisaRequirementType {
  const normalized = visaRequirement.toLowerCase();
  
  if (normalized === "visa required" || normalized === "online visa required") {
    return "VISA_REQUIRED";
  }

  if (normalized === "evisa" || normalized.startsWith("evisa")) {
    return "EVISA";
  }

  if (normalized === "visa on arrival" || normalized.includes("visa on arrival")) {
    return "VISA_ON_ARRIVAL";
  }

  if (normalized === "visa not required") {
    return "VISA_NOT_REQUIRED";
  }

  if (normalized === "freedom of movement") {
    return "FREEDOM_OF_MOVEMENT";
  }

  return null;
}
